logger:
  level: ${log_level}

ota:
  safe_mode: true
  password: !secret ota_password

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  discovery_unique_id_generator: mac
  discovery_object_id_generator: device_name
  topic_prefix: "home/${name}"

web_server:
  port: 80

time:
  platform: sntp
  id: sntp_time

esphome:
  name: ${name}
  on_boot:
    priority: -100.0
    then:
      lambda: id(location).publish_state("${location}");

text_sensor:
  - platform: template
    id: location
    name: "Location"
    update_interval: never
    # lambda: return {"${location}"};

