wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 2
  - ssid: !secret wifi2_ssid
    password: !secret wifi_password
    priority: 1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "${name}"
#    password: !secret ap_password
