esphome:
  name: esp32doit-devkit-v1

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  ssid: "Nerdland"
  password: "dobberml"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Doit-Devkit-V1"
    password: "jfGeFD28zQnL"

ota:
  safe_mode: true
  password: !secret ota_password

captive_portal:

mqtt:
  broker: 192.168.1.208
  topic_prefix: "home/esp32doit-devkit-v1"

web_server:
  port: 80

i2c:

sensor:
  - platform: bmp280
    address: 0x76
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
  - platform: tsl2561
    name: "Ambient Light"
