substitutions:
  name: esp32doit-devkit-v1
  log_level: INFO

esphome:
  name: ${name}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

i2c:

sensor:
  - platform: bmp280
    address: 0x76
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
  - platform: tsl2561
    name: "Ambient Light"
