substitutions:
  name: esp8266-lolin-2
  log_level: INFO
  location: "Main bedroom"

esp8266:
  board: nodemcuv2

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  esp8266_i2c: !include common/esp8266_i2c.yaml

sensor:
  - platform: bme280_i2c
    temperature:
      id: temperature
      name: "Temperature"
    pressure:
      id: pressure
      name: "Pressure"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x76
  - platform: tsl2561
    id: ambient_light
    name: "Ambient Light"
